update(doc_guidelines): update make target to doc8 checker
bao-project/bao-docs pull request #75
Opened 2023-11-06 13:51 UTC by danielRep

## PR Description

Update naming of the doc8 checker target in the documentation. Now is called rst-format and not format.

### Type of change

- **update**: changes that brings a feature, setup, or configuration up to date by adding new or updated information
  - Logical unit: `doc_guidelines.rst`

## Checklist:

- [x] The changes follows the documentation guidelines described in [here](https://github.com/bao-project/bao-docs/blob/main/source/development/doc_guidelines.rst).
- [x] The changes generate no new warnings when building the project. If so, I have justified above.
- [x] I have run the CI checkers before submitting the PR to avoid unnecessary runs of the workflow.

2023-12-04 20:44 UTC, josecm requested changes
Need to change this also in the README file.

2023-12-05 13:19 UTC, danielRep commented
> Need to change this also in the README file.

Done.

2023-12-05 18:19 UTC, josecm approved these changes

2023-12-05 18:24 UTC, miguelafsilva5 approved these changes

2023-12-05 18:29 UTC, merged